### ISSUE TITLE
PPA Not Working Ubuntu 22.04

### ISSUE THREAD

**Issue by InklingGirl** [ilikenwf/apt-fast#201]
When I add the PPA, I get a weird output & it fails to verify the security.
```
Repository: 'deb https://ppa.launchpadcontent.net/apt-fast/stable/ubuntu/ jammy main'
Description:
This PPA contains tested (stable) builds of apt-fast.
More info: https://launchpad.net/~apt-fast/+archive/ubuntu/stable
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/apt-fast-ubuntu-stable-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/apt-fast-ubuntu-stable-jammy.list
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 357, in main
    shortcut.add()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 221, in add
    self.add_source()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 307, in add_source
    sourceslist.save()
  File "/usr/lib/python3/dist-packages/softwareproperties/extendedsourceslist.py", line 391, in save
    with open(filename, "w") as f:
PermissionError: [Errno 1] Operation not permitted: '/etc/apt/sources.list.d/google-earth-pro.list'
```
```
Get:11 https://ppa.launchpadcontent.net/apt-fast/stable/ubuntu jammy InRelease [17.5 kB]
Err:11 https://ppa.launchpadcontent.net/apt-fast/stable/ubuntu jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1EE2FF37CA8DA16B
```
```
W: GPG error: https://ppa.launchpadcontent.net/apt-fast/stable/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1EE2FF37CA8DA16B
E: The repository 'https://ppa.launchpadcontent.net/apt-fast/stable/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by gothicVI** [comment]
Try
```bash
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A2166B8DE8BDC3367D1901C11EE2FF37CA8DA16B
```
as explained in the README.

How did you add the repo?

**Comment by InklingGirl** [comment]
> How did you add the repo?
```
sudo add-apt-repository ppa:apt-fast/stable
sudo apt update
```
As per standard for PPAs.

**Comment by gothicVI** [comment]
> As per standard for PPAs.

That should have added the key. Anyhow, is it solved now?

**Comment by InklingGirl** [comment]
No, the same GPG error occurs.

**Comment by gothicVI** [comment]
Even though you manually added the key?

**Comment by Lasall** [comment]
@InklingGirl Any updates on this?

**Comment by gothicVI** [comment]
I guess this can be closed. Sounds like an error on the user system after all.

**Comment by InklingGirl** [comment]
> @InklingGirl Any updates on this?

I spun up a VM & there's no problem adding the PPA w/ `add-apt-repository`, so it's just that something is wrong w/ my host system.

**Comment by RIABC236** [comment]
This is another reminder that Dominique Lassere aka @Lasall is an abuser who has been bullying me along with his friends in the hate group Storm Ryders.
